### ISSUE TITLE
7월 14일 작업

### ISSUE THREAD

**Issue by JeonB** [JeonB/UniqueGames_v2#28]
- [x] 로그인 페이지 -> 리다이렉트 페이지 제대로 안 되는 문제 수정 - 13일
- [x] DetailMapperController: Notice 의존성 삭제하기 - 14일
- [x] figma 회사리스트 적용 - 14일
- [x]  페이지네이션 적용할 페이지 추가

**Comment by kimbs5899** [comment]
아주 잘하고 계시는군요 좋습니다 예~
